namespace quiz_examination_system
{
    [bindable]
    [default_interface]
    runtimeclass QuestionItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        QuestionItem();
        
        String QuestionId { get; set; };
        String QuestionText { get; set; };
        String DifficultyLevel { get; set; };
        String Topic { get; set; };
        String OptionA { get; set; };
        String OptionB { get; set; };
        String OptionC { get; set; };
        String OptionD { get; set; };
        String CorrectOption { get; set; };
    }
}
