namespace quiz_examination_system
{
    [default_interface]
    runtimeclass QuizManagementItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        QuizManagementItem(String quizId, String title, String teacherName, String createdAt, Int32 attemptCount);
        
        String QuizId { get; };
        String Title { get; };
        String TeacherName { get; };
        String CreatedAt { get; };
        Int32 AttemptCount { get; };
    }
}
